---
- hosts: mesos
  become: true
  become_user: root
  tasks:
  - name: test connection
    ping:
- hosts: local
  tasks:
  - uri: url=http://m1.dcos/mesos/state
    register: result
  - debug: var=result
